# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3849f4482bdaddd55a41462367f00879e7c5b8525ba400436ce55b568a3a17a97017e5cd6ce33467c22a81f9f72c8f43d5292cc2bd759805f1a730e3a71368d1

test:
  secret_key_base: 9d14ed891cc8eee76a867c49e18836095cc929b8b43d38c9d1ff8223b874775642c5d65be20918900886d833f244d8f033e68715e074e42c840f092d5033cb12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
